
// For Rating List
export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];


// For side List
export const dataList = [

  /*For Decoration*/
  {
    id: 1,
    title: 'Event Photography 1',
    serviceTime: '7 days',
    deliveryFee: 700,
    category: 'decoration',
    decoration: 'event',
    rating: 5,
    price: 14500,
    coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2014/10/Event-Photo-02.jpg?w=600&h=1260&ssl=1',
  },
  {
    id: 2,
    title: 'Portrait Photography 1',
    serviceTime: '3 days',
    deliveryFee: 480,
    category: 'decoration',
    decoration: 'portrait',
    rating: 4,
    price: 8500,
    coverSrc: 'https://images.unsplash.com/photo-1606143412458-acc5f86de897?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cG9ydHJhaXQlMjBwaG90b2dyYXBoeXxlbnwwfHwwfHw%3D&w=1000&q=80',
  },
  {
    id: 3,
    title: 'Group Photography 1',
    serviceTime: '2 days',
    deliveryFee: 490,
    category: 'decoration',
    decoration: 'group',
    rating: 3,
    price: 5000,
    coverSrc: 'https://images.squarespace-cdn.com/content/v1/56513229e4b02fdfadb380a8/1534526057969-M55QIATLYGPM2A859B2A/American+Heart+circle+of+RED.+waltz.kenton.jpg?format=1000w',
  },
  {
    id: 4,
    title: 'Event Photography 2',
    serviceTime: '6 days',
    deliveryFee: 250,
    category: 'decoration',
    decoration: 'event',
    rating: 1,
    price: 40000,
    coverSrc: 'https://cdn.shaadiwish.com/img/cat/destination-weddings.jpg',
  },
  {
    id: 5,
    title: 'Portrait Photography 2',
    serviceTime: '3 days',
    deliveryFee: 650,
    category: 'decoration',
    decoration: 'portrait',
    rating: 5,
    price: 9000,
    coverSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhsWFZNiNr3ZCW28N--x3ou34sMDsll6I9mA&usqp=CAU',
  },
  {
    id: 6,
    title: 'Group Photography 2',
    serviceTime: '1 day',
    deliveryFee: 290,
    category: 'decoration',
    decoration: 'group',
    rating: 5,
    price: 6000,
    coverSrc: 'https://ironhoney.com/wp-content/uploads/2015/12/chicago-lifestyle-documentary-event-gala-photographer-39.jpg',
  },



  /*For Catering*/
  //     {
  //       id: 7,
  //       title: 'Nacho cheeseburger',
  //       serviceTime: '50-65min',
  //       deliveryFee: 440,
  //       category: 'catering',
  //       decoration: 'american',
  //       rating: 2,
  //       price: 2200,
  //       coverSrc: 'https://hips.hearstapps.com/del.h-cdn.co/assets/15/24/1434152569-burgers-01.jpg',
  //     },
  //     {
  //       id: 8,
  //       title: 'Meaty Onion Pizza',
  //       serviceTime: '10-15min',
  //       deliveryFee: 250,
  //       category: 'catering',
  //       decoration: 'italian',
  //       rating: 1,
  //       price: 3000,
  //       coverSrc: 'https://1.bp.blogspot.com/-2kLcfQgYOLM/XxDWSlTU1QI/AAAAAAAAQvA/JAFvJPigvXgogs6JlwyBF947oG-mOVeJACLcBGAsYHQ/s1600/FB_IMG_1594938803659.jpg',
  //     },
  //     {
  //       id: 9,
  //       title: 'Shitake Fried Rice',
  //       serviceTime: '12-18min',
  //       deliveryFee: 350,
  //       category: 'catering',
  //       decoration: 'chinese',
  //       rating: 4,
  //       price: 2750,
  //       coverSrc: 'https://static01.nyt.com/images/2011/11/08/health/well_veggie_stir/well_veggie_stir-articleLarge.jpg',
  //     },
  //     {
  //       id: 10,
  //       title: 'Pesto chicken stew',
  //       serviceTime: '30-38min',
  //       deliveryFee: 200,
  //       category: 'catering',
  //       decoration: 'american',
  //       rating: 2,
  //       price: 4350,
  //       coverSrc: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-1085527_11-ad12e39.jpg',
  //     },
  //     {
  //       id: 11,
  //       title: 'Kacchi Biriyani',
  //       serviceTime: '16-20min',
  //       deliveryFee: 400,
  //       category: 'catering',
  //       decoration: 'italian',
  //       rating: 3,
  //       price: 3300,
  //       coverSrc: 'https://www.dhakafoodster.com/wp-content/uploads/2021/06/Sultan%E2%80%99s-Diner-Mirpur-Kacchi-Biriyani-1.jpg',
  //     },
  //     {
  //       id: 12,
  //       title: 'Dim Sums',
  //       serviceTime: '24-30min',
  //       deliveryFee: 500,
  //       category: 'catering',
  //       decoration: 'chinese',
  //       rating: 2,
  //       price: 4100,
  //       coverSrc: 'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2019/09/01125635/262395678_315575290204310_5488398172545455237_n-806x806.jpg',
  //     },
];   