
  // For Rating List
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  
  // For side List
  export const dataList = [
    
    /*For Decoration*/
    {
      id: 1,
      title: 'Event Music 1',
      serviceTime: '7 days',
      deliveryFee: 700,
      category: 'decoration',
      decoration: 'Event',
      rating: 5,
      price: 14500,
      coverSrc: 'https://riverbeats.life/wp-content/uploads/2021/03/24831410_1345703812243189_897870714592809105_o.jpeg',
    },
    {
      id: 2,
      title: 'Official Music 1',
      serviceTime: '3 days',
      deliveryFee: 480,
      category: 'decoration',
      decoration: 'Official',
      rating: 4,
      price: 8500,
      coverSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNdqpkOAySfc2lng50x2qAjfX8BiN2egHedEuGgDxaJ5oWNehXipBsHloDp27AN02_T3I&usqp=CAU',
    },
    {
      id: 3,
      title: 'DJ 1',
      serviceTime: '2 days',
      deliveryFee: 490,
      category: 'decoration',
      decoration: 'DJ',
      rating: 3,
      price: 5000,
      coverSrc: 'https://st.depositphotos.com/1430909/1434/i/450/depositphotos_14345149-stock-photo-dj-mixer-with-headphones.jpg',
    },
    {
      id: 4,
      title: 'Event Music 2',
      serviceTime: '6 days',
      deliveryFee: 250,
      category: 'decoration',
      decoration: 'Event',
      rating: 1,
      price: 40000,
      coverSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxfLmVSfiVYmGhV1YnvjrgOlGx-sdruM6F3Wek8K2SBxAYhPhB39QS7fe1T1BfViqavSM&usqp=CAU',
    },
    {
      id: 5,
      title: 'Official Music 2',
      serviceTime: '3 days',
      deliveryFee: 650,
      category: 'decoration',
      decoration: 'Official',
      rating: 5,
      price: 9000,
      coverSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN9HX5liN-qLuBSO6b5YgOarBWqLiS6Blq5Q&usqp=CAU',
    },
    {
      id: 6,
      title: 'DJ 2',
      serviceTime: '1 day',
      deliveryFee: 290,
      category: 'decoration',
      decoration: 'DJ',
      rating: 5,
      price: 6000,
      coverSrc: 'https://static9.depositphotos.com/1430909/1145/i/950/depositphotos_11452826-stock-photo-dj-mixes-the-track.jpg',
    },
    
    
    
    /*For Catering*/
//     {
//       id: 7,
//       title: 'Nacho cheeseburger',
//       serviceTime: '50-65min',
//       deliveryFee: 440,
//       category: 'catering',
//       decoration: 'american',
//       rating: 2,
//       price: 2200,
//       coverSrc: 'https://hips.hearstapps.com/del.h-cdn.co/assets/15/24/1434152569-burgers-01.jpg',
//     },
//     {
//       id: 8,
//       title: 'Meaty Onion Pizza',
//       serviceTime: '10-15min',
//       deliveryFee: 250,
//       category: 'catering',
//       decoration: 'italian',
//       rating: 1,
//       price: 3000,
//       coverSrc: 'https://1.bp.blogspot.com/-2kLcfQgYOLM/XxDWSlTU1QI/AAAAAAAAQvA/JAFvJPigvXgogs6JlwyBF947oG-mOVeJACLcBGAsYHQ/s1600/FB_IMG_1594938803659.jpg',
//     },
//     {
//       id: 9,
//       title: 'Shitake Fried Rice',
//       serviceTime: '12-18min',
//       deliveryFee: 350,
//       category: 'catering',
//       decoration: 'chinese',
//       rating: 4,
//       price: 2750,
//       coverSrc: 'https://static01.nyt.com/images/2011/11/08/health/well_veggie_stir/well_veggie_stir-articleLarge.jpg',
//     },
//     {
//       id: 10,
//       title: 'Pesto chicken stew',
//       serviceTime: '30-38min',
//       deliveryFee: 200,
//       category: 'catering',
//       decoration: 'american',
//       rating: 2,
//       price: 4350,
//       coverSrc: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-1085527_11-ad12e39.jpg',
//     },
//     {
//       id: 11,
//       title: 'Kacchi Biriyani',
//       serviceTime: '16-20min',
//       deliveryFee: 400,
//       category: 'catering',
//       decoration: 'italian',
//       rating: 3,
//       price: 3300,
//       coverSrc: 'https://www.dhakafoodster.com/wp-content/uploads/2021/06/Sultan%E2%80%99s-Diner-Mirpur-Kacchi-Biriyani-1.jpg',
//     },
//     {
//       id: 12,
//       title: 'Dim Sums',
//       serviceTime: '24-30min',
//       deliveryFee: 500,
//       category: 'catering',
//       decoration: 'chinese',
//       rating: 2,
//       price: 4100,
//       coverSrc: 'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2019/09/01125635/262395678_315575290204310_5488398172545455237_n-806x806.jpg',
//     },
];   