

// For Rating List
export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];


// For side List
export const dataList = [

  /*For Decoration*/
  {
    id: 1,
    name: 'Wedding Decoration 1',
    vendor: "Mim's Company",
    description: 'We are focused on how the venue looks aesthetically. We are the creative professionals who design event spaces with the appropriate organization and decor',
    deliveryFee: 700,
    category: 'decoration',
    decoration: 'wedding',
    serviceTime: '7 days',
    rating: 5,
    price: 24500,
    inform: 'yes',
    Build: '5 hours',
    placement: 'Outdoor',
    space: '20 sq ft',
    guest: 500,
    colors: 'Any',
    customization: 'Allowed',
    coverSrc: 'https://i.pinimg.com/originals/1e/3e/9c/1e3e9c0f92b0ec4aa574f8664129023f.jpg',
  },
  {
    id: 2,
    name: 'Birthday Decoration 1',
    vendor: "Kaniz's Company",
    serviceTime: '3 days',
    deliveryFee: 480,
    category: 'decoration',
    decoration: 'birthday',
    rating: 4,
    price: 8500,
    description: 'We offer a wide range of services to decorate your venue in different ways including: Draping – swathes of fabric that are hung from the ceiling and/or walls in any color scheme creating a soft look',
    inform: 'yes',
    Build: '5 hours',
    placement: 'Outdoor',
    space: '15 sq ft',
    guest: 100,
    colors: 'Black, Blue, Red, White, Pink',
    customization: 'Allowed',
    coverSrc: 'https://m.media-amazon.com/images/I/81nU6clDgEL.jpg',
  },
  {
    id: 3,
    name: 'Proposal Decoration 1',
    vendor: "Mahir's Company",
    serviceTime: '2 days',
    deliveryFee: 490,
    category: 'decoration',
    decoration: 'proposal',
    rating: 3,
    description: 'We are focused on how the venue looks aesthetically. We are the creative professionals who design event spaces with the appropriate organization and decor.',
    price: 5000,
    inform: 'yes',
    Build: '3 hours',
    placement: 'Outdoor',
    space: '10 sq ft',
    guest: 20,
    colors: 'White, Lavender, Pink , Red',
    customization: 'Allowed',
    coverSrc: 'https://i.pinimg.com/736x/b1/75/5b/b1755b280c2c8a1b6a500de9d60988c9.jpg',
  },
  {
    id: 4,
    name: 'Wedding Decoration 2',
    vendor: "Bushra's Company",
    serviceTime: '6 days',
    deliveryFee: 250,
    category: 'decoration',
    decoration: 'wedding',
    rating: 1,
    price: 40000,
    description: 'We offer a wide range of services to decorate your venue in different ways including: Draping – swathes of fabric that are hung from the ceiling and/or walls in any color scheme creating a soft look.',
    inform: 'yes',
    Build: '8 hours',
    placement: 'Outdoor',
    space: '20 sq ft',
    guest: 600,
    colors: 'White, Lavender, Pink , Red, Golden',
    customization: 'Allowed',

    coverSrc: 'https://cdn.shaadiwish.com/img/cat/destination-weddings.jpg',
  },
  {
    id: 5,
    name: 'Birthday Decoration 2',
    vendor: "Momtahina's Company",
    serviceTime: '3 days',
    deliveryFee: 650,
    category: 'decoration',
    decoration: 'birthday',
    rating: 5,
    price: 9000,
    description: 'We are focused on how the venue looks aesthetically. We are the creative professionals who design event spaces with the appropriate organization and decor',
    inform: 'yes',
    Build: '3 hours',
    placement: 'Indoor',
    space: '15 sq ft',
    guest: 100,
    colors: 'Black, Blue, Red, White, Pink',
    customization: 'Allowed',

    coverSrc: 'https://www.fnp.com/images/pr/l/v20210623021345/birthday-balloon-decor-for-husband_1.jpg',
  },
  {
    id: 6,
    name: 'Proposal Decoration 2',
    vendor: "Kaniz's Company",
    serviceTime: '1 day',
    deliveryFee: 290,
    category: 'decoration',
    decoration: 'proposal',
    rating: 5,
    price: 6000,
    description: 'We are focused on how the venue looks aesthetically. We are the creative professionals who design event spaces with the appropriate organization and decor',
    inform: 'yes',
    Build: '3 hours',
    placement: 'Indoor',
    space: '10 sq ft',
    guest: 20,
    colors: 'White, Lavender, Pink , Red',
    customization: 'Allowed',

    coverSrc: 'https://ae01.alicdn.com/kf/S6a00dffb5f3a44fea4dfe9111fc3e1c1R/Wedding-decoration-proposal-props-romantic-scene-layout-confession-room-interior-bag-decoration-Valentine-s-day-party.jpg_Q90.jpg_.webp',
  },

  /*For Catering*/
  {
    id: 7,
    name: 'Wedding Decoration 3',
    vendor: "Bushra's Company",
    serviceTime: '8 days',
    deliveryFee: 440,
    category: 'decoration',
    decoration: 'wedding',
    rating: 5,
    price: 20000,
    description: 'We can create a design that represents everything you are hoping for in an event design. We are also able to create a custom design just for you. Trust us to get the event of your dreams!',
    inform: 'yes',
    Build: '10 hours',
    placement: 'Outdoor',
    space: '20 sq ft',
    guest: 600,
    colors: 'White, Lavender, Pink , Red, Golden',
    customization: 'Allowed',
    coverSrc: 'https://i.pinimg.com/originals/c7/30/2f/c7302f2f6f8b8195b33d628d01958fff.jpg',
  },
  {
    id: 8,
    name: 'Birthday Decoration 3',
    vendor: "Mahir's Company",
    serviceTime: '4 days',
    deliveryFee: 250,
    category: 'decoration',
    decoration: 'birthday',
    rating: 3,
    price: 8000,
    description: 'We can create a design that represents everything you are hoping for in an event design. We are also able to create a custom design just for you. Trust us to get the event of your dreams!',
    inform: 'yes',
    Build: '4 hours',
    placement: 'Indoor',
    space: '7 sq ft',
    guest: 100,
    colors: 'White, Lavender, Pink , Red, Golden',
    customization: 'Allowed',

    coverSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzcIK1_vEoOLeFSUDPkdeJMoxEg4-P_xLHiw&usqp=CAU',
  },
  {
    id: 9,
    name: 'Proposal Decoration 3',
    vendor: "Momtahina's Company",
    serviceTime: '1 days',
    deliveryFee: 490,
    category: 'decoration',
    decoration: 'proposal',
    rating: 3,
    description: 'We are focused on how the venue looks aesthetically. We are the creative professionals who design event spaces with the appropriate organization and decor',
    price: 5000,
    inform: 'yes',
    Build: '3 hours',
    placement: 'Outdoor',
    space: '10 sq ft',
    guest: 20,
    colors: 'White, Lavender, Pink , Red',
    customization: 'Allowed',
    coverSrc: 'https://media.karousell.com/media/photos/products/2022/6/4/romantic_marriage_proposal_dec_1654372631_98577245_progressive.jpg',
  },
  {
    id: 10,
    name: 'Wedding Decoration 4',
    vendor: "Kaniz's Company",
    serviceTime: '6 days',
    deliveryFee: 440,
    category: 'decoration',
    decoration: 'wedding',
    rating: 4,
    price: 20000,
    description: 'We can create a design that represents everything you are hoping for in an event design. We are also able to create a custom design just for you. Trust us to get the event of your dreams!',
    inform: 'yes',
    Build: '8 hours',
    placement: 'Outdoor',
    space: '30 sq ft',
    guest: 800,
    colors: 'White, Lavender, Pink , Red, Golden',
    customization: 'Allowed',
    coverSrc: 'https://assets-news.housing.com/news/wp-content/uploads/2022/01/11220447/wedding-stage-decoration-shutterstock_1193416354-1200x700-compressed-686x400.jpg',
  },
  {
    id: 11,
    name: 'Birthday Decoration 4',
    vendor: "Mahir's Company",
    serviceTime: '4 days',
    deliveryFee: 250,
    category: 'decoration',
    decoration: 'birthday',
    rating: 3,
    price: 8000,
    description: 'We can create a design that represents everything you are hoping for in an event design. We are also able to create a custom design just for you. Trust us to get the event of your dreams!',
    inform: 'yes',
    Build: '3 hours',
    placement: 'Indoor',
    space: '10 sq ft',
    guest: 80,
    colors: 'White, Lavender, Pink , Red, Golden',
    customization: 'Allowed',
    coverSrc: 'https://happybirthdaydecor.com/wp-content/uploads/2022/06/Romantic-Surprise-Birthday-Decoration-Ideas.jpg',
  },
  {
    id: 12,
    name: 'Proposal Decoration 4',
    vendor: "Farida's Company",
    serviceTime: '2 days',
    deliveryFee: 400,
    category: 'decoration',
    decoration: 'proposal',
    rating: 3,
    description: 'We are focused on how the venue looks aesthetically. We are the creative professionals who design event spaces with the appropriate organization and decor',
    price: 4000,
    inform: 'yes',
    Build: '3 hours',
    placement: 'Outdoor',
    space: '5 sq ft',
    guest: 20,
    colors: 'White, Lavender, Pink , Red, Black',
    customization: 'Allowed',
    coverSrc: 'https://media.karousell.com/media/photos/products/2021/6/22/romantic_marriage_proposal_dec_1624399659_373f7106_progressive.jpg',
  },
];
